### ISSUE TITLE
Links on Header

### ISSUE THREAD

**Issue by slockhart1** [Tierneygregory/MyPersonalWebsite#8]
Hi Tierney, I love your website so far, but I found it difficult to click the links on the top bar because the clickable area was only the size of the text. I would recommend trying to increase the hitbox of the links by increasing the padding for each one. That way it is easier to click.

You could also add in a background color change in CSS to go along with the text color change when hovering over the link.

**Comment by Tierneygregory** [comment]
okay good idea!
