### ISSUE TITLE
Picture + paragraphs

### ISSUE THREAD

**Issue by slockhart1** [Tierneygregory/MyPersonalWebsite#9]
I like the way all of your content pages look but I feel like they could be better if there was a horizontal margin between each of the images and paragraphs above and below each other. That way, content would be more separated and easier for the eyes to read. 

You can achieve this by editing the span between each row. I am not too familiar with this function but it could help to separate out the rows. 

Another strategy you could do would be pairing each image and paragraph in its own div with a matching class to the rest of the divs of the same type. That way, you edit the formatting for all divs by only changing one part of the CSS code.

**Comment by Tierneygregory** [comment]
Hi! Thank you! i tried my best to space it!thank you!
